### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Akruidenberg** [niclaslindstedt/docker-backup#2]
It would be nice to have notifications when the backup is completed, or have some errors.

**Comment by niclaslindstedt** [comment]
I agree. How would you prefer to get notifications? E-mails?

**Comment by niclaslindstedt** [comment]
Thinking about the following:

1. Slack notifications
2. E-mail notifications (with curl + nslookup/dig)
3. Webhook notifications (pre-defined data structure sent to a webhook url -- that way anyone can do any further implementation needed for their specific needs).

**Comment by niclaslindstedt** [comment]
Opened new issue for e-mails #47
